language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kootiktok/docker-nginx -f Dockerfile.dev .

script:
  - docker run e CI=true kootiktok/docker-nginx npm run test -- --coverage
