language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kootiktok/docker-nginx -f Dockerfile.dev .

script:
  - docker run -e CI=true kootiktok/docker-nginx npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-nginx'
  env: 'DockerNginx-env'
  bucket_name: 'elasticbeanstalk-us-east-2-593361893208'
  bucket_path: 'docker-nginx'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
